# Generated by Django 5.2.8 on 2025-11-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_alter_source_id_alter_userincome_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userincome',
            old_name='owner',
            new_name='user',
        ),
    ]
