# Generated by Django 5.2.8 on 2025-11-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0003_rename_owner_userincome_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='userincome',
            old_name='user',
            new_name='owner',
        ),
    ]
